### ISSUE TITLE
question about  train FVC 

### ISSUE THREAD

**Issue by WenBingo** [ZhihaoHu/PyTorchVideoCompression#21]
when i run the main.py  , it trackback  blow:

Traceback (most recent call last):
  File "E:\Code_of_shenbin\code_of_reconfiguration\Video\FVC\main.py", line 290, in <module>
    global_step = train(epoch, global_step)
  File "E:\Code_of_shenbin\code_of_reconfiguration\Video\FVC\main.py", line 190, in train
    seqout["rd_loss"].backward()
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\autograd\__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\autograd\function.py", line 274, in apply
    return user_fn(self, *args)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\autograd\function.py", line 522, in wrapper
    outputs = fn(ctx, *args)
  File "E:\Code_of_shenbin\code_of_reconfiguration\Video\FVC\subnet\dcn\deform_conv.py", line 73, in backward
    deform_conv_cuda.deform_conv_backward_parameters_cuda(
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

and when i run the /dcn/setup.py   it traceback :

  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by lsw28** [comment]
I have also encountered a similar problem. Have you solved it
