### ISSUE TITLE
Unable to reproduce experimental results in the paper.

### ISSUE THREAD

**Issue by RongRongRongRong** [ZhihaoHu/PyTorchVideoCompression#27]
I downloaded the UVG dataset with 1080p video clips and tested it with a pre-trained 2048.model, but was unable to reproduce the experimental results in the paper.

Here is the relevant data:
Ipp=[1.2929020996093752, 0.94005859375, 0.7543700358072918, 0.6924034016927084, 0.6758680826822915, 0.6770526529947917, 0.8640651041666668]

test result:[ average bpp : 0.174915, average psnr : 36.798520, average msssim: 0.948412]

Alternatively, we trained ourselves to produce results that are not far from this one. 

I'd like to ask if there's a problem with my data processing or with the training methodology.

**Comment by PureEyeHeart** [comment]
Hello, I want to ask how you conducted the test, I reported an error here
“model parameter :  21049427
loading pretrain :  F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\snapshot\1024.model
testing UVG Dataset : 
Testing UVG dataset using I frame : BPGQ20
Traceback (most recent call last):
  File "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\main.py", line 285, in <module>
    Test("UVG dataset", test_dataset, 0, testfull=True)
  File "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\main.py", line 101, in Test
    for batch_idx, inputs in enumerate(test_loader):
  File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py", line 634, in __next__
    data = self._next_data()
  File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\dataset.py", line 72, in __getitem__
    ref_image = imageio.imread(self.ref[index]).transpose(2, 0, 1).astype(np.float32) / 255.0
  File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\v2.py", line 359, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\core\imopen.py", line 113, in imopen
    request = Request(uri, io_mode, format_hint=format_hint, extension=extension)
  File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\core\request.py", line 249, in __init__
    self._parse_uri(uri)
  File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\core\request.py", line 409, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: 'F:\python_project\PyTorchVideoCompression-master\FVC\data\UVG\images\Beauty\BPGQ20\im0001.png'


Process finished with exit code 1
”

**Comment by RongRongRongRong** [comment]
> Hello, I want to ask how you conducted the test, I reported an error here “model parameter : 21049427 loading pretrain : F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\snapshot\1024.model testing UVG Dataset : Testing UVG dataset using I frame : BPGQ20 Traceback (most recent call last): File "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\main.py", line 285, in Test("UVG dataset", test_dataset, 0, testfull=True) File "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\main.py", line 101, in Test for batch_idx, inputs in enumerate(test_loader): File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py", line 634, in **next** data = self._next_data() File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data return self._process_data(data) File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data data.reraise() File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch_utils.py", line 644, in reraise raise exception FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0. Original Traceback (most recent call last): File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data_utils\worker.py", line 308, in _worker_loop data = fetcher.fetch(index) File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data_utils\fetch.py", line 51, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data_utils\fetch.py", line 51, in data = [self.dataset[idx] for idx in possibly_batched_index] File "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\dataset.py", line 72, in **getitem** ref_image = imageio.imread(self.ref[index]).transpose(2, 0, 1).astype(np.float32) / 255.0 File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio__init__.py", line 97, in imread return imread_v2(uri, format=format, **kwargs) File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\v2.py", line 359, in imread with imopen(uri, "ri", **imopen_args) as file: File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\core\imopen.py", line 113, in imopen request = Request(uri, io_mode, format_hint=format_hint, extension=extension) File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\core\request.py", line 249, in **init** self._parse_uri(uri) File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\core\request.py", line 409, in _parse_uri raise FileNotFoundError("No such file: '%s'" % fn) FileNotFoundError: No such file: 'F:\python_project\PyTorchVideoCompression-master\FVC\data\UVG\images\Beauty\BPGQ20\im0001.png'
> 
> Process finished with exit code 1 ”

It seems to be that you didn't follow his testing process to decode the video to picture correctly, did you skip any test data preparation step?

**Comment by wsh0711** [comment]
> Hello, I want to ask how you conducted the test, I reported an error here你好，我想询问你是如何进行测试的，我在这里报告了一个错误 “model parameter : 21049427“模型参数：21049427 loading pretrain : F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\snapshot\1024.model 加载预训练模型：F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\snapshot\1024.model testing UVG Dataset :测试 UVG 数据集： Testing UVG dataset using I frame : BPGQ20使用 I 帧测试 UVG 数据集：BPGQ20 Traceback (most recent call last): File "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\main.py", line 285, in 文件 "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\main.py"，第 285 行，在 Test("UVG dataset", test_dataset, 0, testfull=True) Test("UVG 数据集", test_dataset, 0, testfull=True) File "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\main.py", line 101, in Test文件 "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\main.py"，第 101 行，在 Test 中 for batch_idx, inputs in enumerate(test_loader): File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py", line 634, in **next**文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py"，第 634 行，在 next 中 data = self._next_data() File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py"，第 1346 行，在_next_data 中 return self._process_data(data)返回 self._process_data(data) File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py"，第 1372 行，在_process_data 中 data.reraise() File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch_utils.py", line 644, in reraise文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch_utils.py"，第 644 行，在 reraise 中 raise exception FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.FileNotFoundError: 在 DataLoader 工作进程 0 中捕获到 FileNotFoundError。 Original Traceback (most recent call last):原始回溯（最近调用最后）： File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data_utils\worker.py", line 308, in _worker_loop文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data_utils\worker.py"，第 308 行，在 worker_loop 函数中 data = fetcher.fetch(index) File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data_utils\fetch.py", line 51, in fetch文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data_utils\fetch.py"，第 51 行，在 fetch 函数中 data = [self.dataset[idx] for idx in possibly_batched_index] File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data_utils\fetch.py", line 51, in 文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data_utils\fetch.py"，第 51 行 data = [self.dataset[idx] for idx in possibly_batched_index] File "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\dataset.py", line 72, in **getitem**文件 "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\dataset.py"，第 72 行，在 getitem 中 ref_image = imageio.imread(self.ref[index]).transpose(2, 0, 1).astype(np.float32) / 255.0 File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio__init__.py", line 97, in imread文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio_init.py"，第 97 行，在 imread 函数中 return imread_v2(uri, format=format, **kwargs) File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\v2.py", line 359, in imread文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\v2.py"，第 359 行，在 imread 中 with imopen(uri, "ri", **imopen_args) as file: File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\core\imopen.py", line 113, in imopen文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\core\imopen.py"，第 113 行，在 imopen 函数中 request = Request(uri, io_mode, format_hint=format_hint, extension=extension) File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\core\request.py", line 249, in **init**文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\core\request.py"，第 249 行，在 init 函数中 self._parse_uri(uri) File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\core\request.py", line 409, in _parse_uri raise FileNotFoundError("No such file: '%s'" % fn) FileNotFoundError: No such file: 'F:\python_project\PyTorchVideoCompression-master\FVC\data\UVG\images\Beauty\BPGQ20\im0001.png'FileNotFoundError: 找不到文件：'F:\python_project\PyTorchVideoCompression-master\FVC\data\UVG\images\Beauty\BPGQ20\im0001.png'
> 
> Process finished with exit code 1进程以退出代码 1 完成 ”



> Hello, I want to ask how you conducted the test, I reported an error here你好，我想询问你是如何进行测试的，我在这里报告了一个错误 “model parameter : 21049427“模型参数：21049427 loading pretrain : F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\snapshot\1024.model 加载预训练模型：F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\snapshot\1024.model testing UVG Dataset :测试 UVG 数据集： Testing UVG dataset using I frame : BPGQ20使用 I 帧测试 UVG 数据集：BPGQ20 Traceback (most recent call last): File "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\main.py", line 285, in 文件 "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\main.py"，第 285 行，在 Test("UVG dataset", test_dataset, 0, testfull=True) Test("UVG 数据集", test_dataset, 0, testfull=True) File "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\main.py", line 101, in Test文件 "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\main.py"，第 101 行，在 Test 中 for batch_idx, inputs in enumerate(test_loader): File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py", line 634, in **next**文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py"，第 634 行，在 next 中 data = self._next_data() File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py"，第 1346 行，在_next_data 中 return self._process_data(data)返回 self._process_data(data) File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data\dataloader.py"，第 1372 行，在_process_data 中 data.reraise() File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch_utils.py", line 644, in reraise文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch_utils.py"，第 644 行，在 reraise 中 raise exception FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.FileNotFoundError: 在 DataLoader 工作进程 0 中捕获到 FileNotFoundError。 Original Traceback (most recent call last):原始回溯（最近调用最后）： File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data_utils\worker.py", line 308, in _worker_loop文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data_utils\worker.py"，第 308 行，在 worker_loop 函数中 data = fetcher.fetch(index) File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data_utils\fetch.py", line 51, in fetch文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data_utils\fetch.py"，第 51 行，在 fetch 函数中 data = [self.dataset[idx] for idx in possibly_batched_index] File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data_utils\fetch.py", line 51, in 文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\torch\utils\data_utils\fetch.py"，第 51 行 data = [self.dataset[idx] for idx in possibly_batched_index] File "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\dataset.py", line 72, in **getitem**文件 "F:\python_project\PyTorchVideoCompression-master\FVC\examples\example\savecode\dataset.py"，第 72 行，在 getitem 中 ref_image = imageio.imread(self.ref[index]).transpose(2, 0, 1).astype(np.float32) / 255.0 File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio__init__.py", line 97, in imread文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio_init.py"，第 97 行，在 imread 函数中 return imread_v2(uri, format=format, **kwargs) File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\v2.py", line 359, in imread文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\v2.py"，第 359 行，在 imread 中 with imopen(uri, "ri", **imopen_args) as file: File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\core\imopen.py", line 113, in imopen文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\core\imopen.py"，第 113 行，在 imopen 函数中 request = Request(uri, io_mode, format_hint=format_hint, extension=extension) File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\core\request.py", line 249, in **init**文件 "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\core\request.py"，第 249 行，在 init 函数中 self._parse_uri(uri) File "D:\Anaconda\envs\VideoCompression_master_env\lib\site-packages\imageio\core\request.py", line 409, in _parse_uri raise FileNotFoundError("No such file: '%s'" % fn) FileNotFoundError: No such file: 'F:\python_project\PyTorchVideoCompression-master\FVC\data\UVG\images\Beauty\BPGQ20\im0001.png'FileNotFoundError: 找不到文件：'F:\python_project\PyTorchVideoCompression-master\FVC\data\UVG\images\Beauty\BPGQ20\im0001.png'
> 
> Process finished with exit code 1进程以退出代码 1 完成 ”

Hello, I also encountered this problem. And when I was trying to generate I frames, I encountered other errors as follows: RuntimeWarning:，RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
nan
 Mean of empty sliceThe generated bpp is a nan value and is not usable. May I ask if you have solved this problem later, or have you encountered and resolved this error? I would like to receive your reply.
