### ISSUE TITLE
Problem with torchac

### ISSUE THREAD

**Issue by Neetusigger** [ZhihaoHu/PyTorchVideoCompression#3]
I am trying to run testing part. When I tried sh run.sh or sh test.sh then got the error -

Using /home/neetu/.cache/torch_extensions as PyTorch extensions root...
Traceback (most recent call last):
  File "savecode//main.py", line 8, in <module>
    from net import *
  File "/mnt/c/users/2004062.local/desktop/python/savecode/DVC/examples/example/savecode/net.py", line 16, in <module>
    import torchac
  File "/home/neetu/anaconda3/envs/myenv/lib/python3.6/site-packages/torchac/_init_.py", line 2, in <module>
    from torchac.torchac import encode_float_cdf
  File "/home/neetu/anaconda3/envs/myenv/lib/python3.6/site-packages/torchac/torchac.py", line 16, in <module>
    verbose=True)
  File "/home/neetu/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1092, in load
    keep_intermediates=keep_intermediates)
  File "/home/neetu/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1303, in _jit_compile
    is_standalone=is_standalone)
  File "/home/neetu/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1379, in _write_ninja_file_and_build_library
    check_compiler_abi_compatibility(compiler)
  File "/home/neetu/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 283, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/home/neetu/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 243, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/home/neetu/anaconda3/envs/myenv/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/home/neetu/anaconda3/envs/myenv/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.

If you can help me . Thank you.

**Comment by pavan-dharimireddy** [comment]
i don't know whether this may solve your problem, whereever you find the torchac, change torchac to torch_ac
"pip install torch-ac"

**Comment by CamaroTheBOSS** [comment]
You probably doesn't have C++ and C++ compiler to compile the c++ backend used in torchac, so you need to install it

**Comment by yitai-cheng** [comment]
> i don't know whether this may solve your problem, whereever you find the torchac, change torchac to torch_ac "pip install torch-ac"

Hi, Did you generate the result described by the paper using torch-ac?

**Comment by siggerneetu** [comment]
Yes it is working for  me know.
